name: Parallel rspec

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [1, 2, 3]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install rs command
      run: sudo apt-get install rs
    - name: Install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Test
      run: |
        ls -1 spec/* | xargs -n3 | rs -T | sed -n "s/^/bundle exec rspec --format RspecHtmlReporter /; ${{ matrix.node }}p" | bash
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: reports
        path: reports
    - name: Download
      uses: actions/download-artifact@master
      with:
        name: reports
    - name: Print
      run: |
        ls reports
