name: Rspec knapsack

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [0, 1, 2]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Test
      env:
        CI_NODE_TOTAL: 3
        CI_NODE_INDEX: ${{ matrix.node }}
      run: |
        bundle exec knapsack rspec --format RspecHtmlReporter spec/**
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: reports
        path: reports
