name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [1, 2, 3]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install rs command
      run: sudo apt-get install rs
    - name: Build and test
      env:
        CI_NODE_TOTAL: 3
        CI_NODE_INDEX: ${{ matrix.node }}
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec knapsack rspec spec/**
